// ═══════════════════════════════════════════════════
// EATJOYcook 食研所·爆食戰線 遊戲引擎
// 注意：本檔案需與 index.html 放在同一目錄
// GAME_HTML_STATIC = 遊戲 HTML + CSS 靜態模板
// GAME_JS_BODY     = 遊戲 JS 引擎程式碼
// ═══════════════════════════════════════════════════

// ── 遊戲 HTML 靜態模板 ──────────────────────────────
var GAME_HTML_STATIC = [
  '<!DOCTYPE html>',
  '<html lang="zh-TW">',
  '<head>',
  '<meta charset="UTF-8">',
  '<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">',
  '<title>食研所 爆食戰線</title>',
  '<style>',
  '*{box-sizing:border-box;margin:0;padding:0;-webkit-tap-highlight-color:transparent}',
  'html,body{width:100%;height:100%;overflow:hidden;background:#f5f0e8;font-family:\'Segoe UI\',sans-serif;color:#3d2b1f;touch-action:none}',
  '#gc{position:relative;width:100%;height:100%;background:#fdf8f0;overflow:hidden}',
  'canvas{display:block;width:100%;height:100%}',
  '/* ── HUD ── */',
  '#hud{position:absolute;top:0;left:0;right:0;padding:8px 10px 8px 10px;display:flex;align-items:flex-start;justify-content:space-between;z-index:20;background:linear-gradient(rgba(253,248,240,.96),transparent 90%)}',
  '#charBars{display:flex;flex-direction:column;gap:2px;pointer-events:auto}',
  '.charBar{display:flex;align-items:center;gap:4px;margin-bottom:0px}',
  '.charBarEmoji{font-size:12px;flex-shrink:0}',
  '.charBarInfo{display:flex;flex-direction:column;gap:1px}',
  '.charBarName{font-size:8px;font-weight:900;color:#92400e;white-space:nowrap}',
  '.charBarTrack{width:88px;height:9px;background:#fee2e2;border-radius:5px;border:1px solid #fca5a5;overflow:hidden}',
  '.charBarFill{height:100%;border-radius:7px;transition:width .2s}',
  '.charBarNum{font-size:8px;font-weight:900;color:#dc2626}',
  '#stamRow{display:flex;align-items:center;gap:3px;margin-top:2px}',
  '#stamTrack{width:88px;height:7px;background:#dcfce7;border-radius:4px;border:1px solid #86efac;overflow:hidden}',
  '#stamFill{height:100%;border-radius:6px;transition:width .15s;background:linear-gradient(90deg,#22c55e,#86efac)}',
  '#stamNum{font-size:8px;font-weight:900;color:#16a34a}',
  '.hM{text-align:center;pointer-events:none;flex-shrink:0}',
  '#formBadge{display:block;font-size:15px;font-weight:900;color:#92400e;background:rgba(251,191,36,.18);border-radius:10px;padding:3px 10px}',
  '#formPassive{font-size:11px;color:#7c3aed;font-weight:700}',
  '.hR{position:absolute;top:6px;right:8px;text-align:right;font-size:13px;font-weight:900;line-height:1;color:#78350f;z-index:22;display:flex;flex-direction:column;gap:4px;align-items:flex-end}',
  '/* Boss HUD */',
  '#bossHud{position:absolute;top:88px;left:50%;transform:translateX(-50%);width:90%;max-width:460px;z-index:20;pointer-events:none;display:none}',
  '#bossName{text-align:center;font-size:18px;font-weight:900;color:#b91c1c;margin-bottom:6px}',
  '#bossTrack{height:18px;background:#fee2e2;border-radius:9px;border:2px solid #f87171;overflow:hidden}',
  '#bossFill{height:100%;background:linear-gradient(90deg,#ef4444,#f97316);border-radius:8px;transition:width .25s}',
  '/* Skill row */',
  '#skillRow{display:none}',
  '.skBadge{width:70px;height:70px;border-radius:20px;border:3px solid #d97706;background:rgba(253,248,240,.95);display:flex;align-items:center;justify-content:center;font-size:30px;position:relative;cursor:pointer;box-shadow:0 3px 12px rgba(180,83,9,.25)}',
  '.skCd{display:none!important}',
  '/* ── 搖桿（左下） ── */',
  '#joystickWrap{position:absolute;left:14px;bottom:18px;width:140px;height:140px;z-index:20}',
  '#joystickBase{position:absolute;inset:0;border-radius:50%;background:rgba(253,248,240,.78);border:3px solid rgba(217,119,6,.45);box-shadow:0 4px 18px rgba(0,0,0,.18)}',
  '#joystickThumb{position:absolute;width:58px;height:58px;border-radius:50%;background:radial-gradient(circle at 38% 38%,rgba(253,248,240,.98),rgba(253,220,160,.92));border:2px solid #d97706;box-shadow:0 4px 14px rgba(0,0,0,.28);top:50%;left:50%;transform:translate(-50%,-50%);touch-action:none}',
  '/* ── 角色切換欄（右側中間，直排） ── */',
  '#charSwitchBar{position:absolute;right:14px;top:50%;transform:translateY(-60%);display:flex;flex-direction:column;gap:8px;z-index:25}',
  '.cSwBtn{display:flex;flex-direction:column;align-items:center;gap:2px;padding:7px 5px;border-radius:14px;border:2px solid #e5e7eb;background:rgba(253,248,240,.95);cursor:pointer;width:68px;transition:all .15s;box-shadow:0 2px 8px rgba(0,0,0,.12)}',
  '.cSwBtn.active-char{border-color:#f59e0b;background:rgba(251,191,36,.3);box-shadow:0 0 20px rgba(245,158,11,.55)}',
  '.cSwBtn.dead-char{opacity:.32;filter:grayscale(1);cursor:not-allowed}',
  '.cSwEmoji{font-size:24px;line-height:1}',
  '.cSwName{font-size:10px;font-weight:900;color:#92400e;max-width:60px;overflow:hidden;white-space:nowrap;text-overflow:ellipsis;text-align:center}',
  '.cSwHpTrack{width:56px;height:7px;background:#e5e7eb;border-radius:4px;overflow:hidden}',
  '.cSwHpFill{height:100%;background:#22c55e;border-radius:4px;transition:width .2s}',
  '.cSwDead{font-size:16px;color:#9ca3af;display:none}',
  '/* ── 右側主控制（右下） ── */',
  '#rightCtrl{position:absolute;right:8px;bottom:12px;display:flex;flex-direction:column;align-items:flex-end;gap:8px;z-index:20}',
  '.rBtn{width:72px;height:72px;border-radius:20px;border:3px solid;background:rgba(253,248,240,.95);display:flex;align-items:center;justify-content:center;font-size:32px;cursor:pointer;font-weight:900;position:relative;box-shadow:0 3px 12px rgba(0,0,0,.18)}',
  '.rBtn:active{opacity:.65;transform:scale(.92)}',
  '.skRow{display:flex;gap:6px}',
  '#wpnToggle{border-color:#dc2626;background:rgba(220,38,38,.15);border-radius:20px}',
  '#dodgeBtn{border-color:#2563eb;background:rgba(37,99,235,.15);border-radius:20px}',
  '#sk1Wrap{border-color:#16a34a;background:rgba(22,163,74,.15);border-radius:20px}',
  '#sk2Wrap{border-color:#16a34a;background:rgba(22,163,74,.1);border-radius:20px}',
  '/* Toast */',
  '#toast{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);background:rgba(253,248,240,.97);border:2px solid #d97706;border-radius:20px;padding:18px 24px;text-align:center;font-size:16px;font-weight:900;color:#92400e;z-index:60;pointer-events:none;opacity:0;transition:opacity .3s;line-height:1.7;max-width:85%;box-shadow:0 5px 24px rgba(0,0,0,.18)}',
  '/* Back btn */',
  '#backBtn{display:none}',
  '/* QA Overlay */',
  '#qaOverlay{position:absolute;inset:0;z-index:80;display:none;pointer-events:none}',
  '#qaCard{position:absolute;top:10px;left:50%;transform:translateX(-50%);width:90%;max-width:360px;background:rgba(253,248,240,.97);border:2px solid #d97706;border-radius:14px;padding:12px 16px;z-index:82;pointer-events:none;box-shadow:0 4px 20px rgba(0,0,0,.18)}',
  '#qaText{font-size:19px;font-weight:900;color:#78350f;text-align:center;line-height:1.5;margin-bottom:8px}',
  '#timerBar{width:100%;height:7px;background:#fde8c8;border-radius:4px;overflow:hidden}',
  '#timerFill{height:100%;background:linear-gradient(90deg,#22c55e,#eab308,#ef4444);border-radius:4px;transition:width .1s linear}',
  '#timerLabel{text-align:center;font-size:12px;color:#92400e;margin-top:3px;font-weight:700}',
  '#qaZones{position:absolute;inset:0;display:grid;grid-template-columns:1fr 1fr 1fr 1fr;grid-template-rows:1fr;z-index:81;pointer-events:none}',
  '.qzone{display:flex;flex-direction:column;align-items:center;justify-content:center;position:relative;border:1px solid rgba(255,255,255,.1)}',
  '.qzone .zLetter{font-size:80px;font-weight:900;opacity:.18;position:absolute;top:50%;left:50%;transform:translate(-50%,-50%)}',
  '.qzone .zLabel{position:absolute;bottom:8%;font-size:18px;font-weight:900;text-align:center;padding:0 8px;line-height:1.4;text-shadow:0 2px 4px rgba(0,0,0,.6);width:100%}',
  '#zA{background:rgba(167,139,250,.2);color:#7c3aed}#zA .zLetter{color:#7c3aed}',
  '#zB{background:rgba(34,197,94,.2);color:#15803d}#zB .zLetter{color:#15803d}',
  '#zC{background:rgba(59,130,246,.2);color:#1d4ed8}#zC .zLetter{color:#1d4ed8}',
  '#zD{background:rgba(249,115,22,.2);color:#c2410c}#zD .zLetter{color:#c2410c}',
  '.qzone.cf{animation:cf .6s ease-out}@keyframes cf{0%{background:rgba(74,222,128,.5)}100%{}}',
  '.qzone.wf{animation:wf .5s ease-out}@keyframes wf{0%{background:rgba(239,68,68,.5)}100%{}}',
  '#pzr{position:absolute;width:56px;height:56px;border-radius:50%;border:4px solid #facc15;box-shadow:0 0 18px #facc15;pointer-events:none;z-index:83;display:none}',
  '/* Modals */',
  '.modal{position:absolute;inset:0;background:rgba(61,43,31,.6);display:flex;align-items:center;justify-content:center;z-index:100;backdrop-filter:blur(6px)}',
  '.mbox{background:#fdf8f0;border:2px solid #d97706;border-radius:22px;padding:24px 20px;max-width:320px;width:92%;text-align:center;max-height:92vh;overflow-y:auto;box-shadow:0 8px 32px rgba(0,0,0,.2)}',
  '.mbox h2{font-size:26px;font-weight:900;color:#92400e;margin-bottom:10px}',
  '.mbox p{font-size:16px;color:#78350f;line-height:1.7;margin-bottom:18px}',
  '.mbtn{width:100%;padding:14px;border-radius:14px;border:2px solid;font-size:16px;font-weight:900;cursor:pointer;margin-bottom:8px}',
  '.mbtn.blue{background:linear-gradient(135deg,#fef3c7,#fde68a);border-color:#d97706;color:#92400e}',
  '.mbtn.red{background:linear-gradient(135deg,#fee2e2,#fecaca);border-color:#dc2626;color:#991b1b}',
  '.mbtn.grey{background:#f5f0e8;border-color:#a8a29e;color:#57534e}',
  '#revProg{display:flex;gap:7px;justify-content:flex-start;margin-bottom:10px}',
  '.quizOpts{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}',
  '.qopt{padding:13px 10px;border-radius:13px;border:2px solid #d6d3d1;background:#fdf8f0;color:#3d2b1f;font-size:16px;font-weight:900;cursor:pointer;text-align:left;line-height:1.5}',
  '.qopt:active{background:#fef3c7}',
  '.qopt.correct{border-color:#16a34a!important;background:#dcfce7!important;color:#14532d!important}',
  '.qopt.wrong{border-color:#dc2626!important;background:#fee2e2!important;color:#991b1b!important}',
  '/* Stage flash */',
  '#stageFlash{position:absolute;inset:0;display:none;align-items:center;justify-content:center;z-index:70;pointer-events:none}',
  '</style>',
  '</head>',
  '<body>',
  '<div id="gc">',
  '<canvas id="gameCanvas"></canvas>',
  '<div id="hud">',
  '<div>',
  ' <div id="charBars"></div>',
  ' <div id="stamRow"><div style="font-size:13px">⚡</div><div id="stamTrack"><div id="stamFill" style="width:100%"></div></div><div id="stamNum"></div></div>',
  '</div>',
  '<div class="hM"><span id="formBadge">🍙 原味</span><br><span id="formPassive">✨ 普通型</span></div>',
  '<div class="hR"><span style="background:rgba(233,109,42,.12);border-radius:8px;padding:2px 7px;color:#e96d2a;font-size:12px;white-space:nowrap">💰 <span id="coinDisp">0</span></span><span style="background:rgba(124,58,237,.1);border-radius:8px;padding:2px 7px;color:#7c3aed;font-size:12px;white-space:nowrap">🏆 <span id="scoreDisp">0</span></span><span style="background:rgba(5,150,105,.1);border-radius:8px;padding:2px 7px;color:#059669;font-size:12px;white-space:nowrap">LV<span id="lvlDisp">1</span></span></div>',
  '</div>',
  '<div id="skillRow">',
  '<div class="skBadge" id="skP"><span id="skPI">✨</span></div>',
  '</div>',
  '<!-- 搖桿（左下） -->',
  '<div id="joystickWrap"><div id="joystickBase"></div><div id="joystickThumb"></div></div>',
  '<!-- 角色切換欄（右側中間） -->',
  '<div id="charSwitchBar">',
  '<div class="cSwBtn" id="csBtn0" onclick="switchToChar(0)"><div class="cSwEmoji" id="csEmoji0">🐾</div><div class="cSwName" id="csName0">—</div><div class="cSwHpTrack"><div class="cSwHpFill" id="csHpFill0" style="width:100%"></div></div><div class="cSwDead" id="csDead0">💀</div></div>',
  '<div class="cSwBtn" id="csBtn1" onclick="switchToChar(1)"><div class="cSwEmoji" id="csEmoji1">🐾</div><div class="cSwName" id="csName1">—</div><div class="cSwHpTrack"><div class="cSwHpFill" id="csHpFill1" style="width:100%"></div></div><div class="cSwDead" id="csDead1">💀</div></div>',
  '<div class="cSwBtn" id="csBtn2" onclick="switchToChar(2)"><div class="cSwEmoji" id="csEmoji2">🐾</div><div class="cSwName" id="csName2">—</div><div class="cSwHpTrack"><div class="cSwHpFill" id="csHpFill2" style="width:100%"></div></div><div class="cSwDead" id="csDead2">💀</div></div>',
  '</div>',
  '<div id="bossHud"><div id="bossName">👿 魔王</div><div id="bossTrack"><div id="bossFill" style="width:100%"></div></div><div id="bossShieldTrack" style="width:100%;height:7px;background:#1e3a5f;border-radius:3px;overflow:hidden;margin-top:3px"><div id="bossShieldBar" style="height:100%;width:100%;background:linear-gradient(90deg,#93c5fd,#3b82f6);border-radius:3px;transition:width .2s"></div></div><div id="bossShieldLbl" style="font-size:9px;color:#93c5fd;text-align:right">🛡️</div></div>',
  '<div id="toast"></div>',
  '<div id="qaOverlay">',
  '<div id="qaZones">',
  ' <div id="zA" class="qzone"><span class="zLetter">A</span><span class="zLabel" id="zAL"></span></div>',
  ' <div id="zB" class="qzone"><span class="zLetter">B</span><span class="zLabel" id="zBL"></span></div>',
  ' <div id="zC" class="qzone"><span class="zLetter">C</span><span class="zLabel" id="zCL"></span></div>',
  ' <div id="zD" class="qzone"><span class="zLetter">D</span><span class="zLabel" id="zDL"></span></div>',
  '</div>',
  '<div id="pzr"></div>',
  '<div id="qaCard"><div id="qaText">問題</div><div id="timerBar"><div id="timerFill" style="width:100%"></div></div><div id="timerLabel">5.0s</div></div>',
  '</div>',
  '<!-- 右側控制（右下） -->',
  '<div id="rightCtrl">',
  '<div id="wpnToggle" class="rBtn" onclick="toggleWeapon()">🏹</div>',
  '<div id="dodgeBtn" class="rBtn" onclick="doDodge()">💨</div>',
  '<div class="skRow">',
  ' <div class="skBadge" id="sk1" onclick="useSkill1()"><span id="sk1I">⚡</span><div class="skCd" id="sk1Cd" style="display:none"></div></div>',
  ' <div class="skBadge" id="sk2" onclick="useSkill2()"><span id="sk2I">🌟</span><div class="skCd" id="sk2Cd" style="display:none"></div></div>',
  '</div>',
  '</div>',
  '<!-- Modals -->',
  '<div class="modal" id="startModal">',
  '<div class="mbox">',
  ' <div style="font-size:52px;margin-bottom:8px" id="startEmoji">🍙</div>',
  ' <h2>食研所 · 爆食戰線</h2>',
  ' <p>🕹️搖桿移動　👿魔王掉100金幣<br>💨迴避　⚔️切換近戰/遠程<br><b style="color:#92400e">魔王大絕→移到正確答案區！</b><br>全員陣亡後答對5題才能帶戰利品回營地</p>',
  ' <div id="partnerPreview" style="font-size:12px;color:#059669;font-weight:900;margin-bottom:10px"></div>',
  ' <button class="mbtn blue" onclick="startGame()">⚔️ 出征！</button>',
  '</div>',
  '</div>',
  '<div class="modal" id="revModal" style="display:none">',
  '<div class="mbox">',
  ' <div style="font-size:32px;margin-bottom:4px">💊</div>',
  ' <h2>醫治復活</h2>',
  ' <p style="font-size:14px;margin-bottom:8px;line-height:1.6">答對 5 題帶著戰利品<b style="color:#059669">回到營地</b><br>⚠️ 答錯 3 題 → 金幣與裝備全數遺失！</p>',
  ' <div id="charStatusRow" style="display:flex;justify-content:center;gap:12px;margin-bottom:10px"></div>',
  ' <div style="margin-bottom:6px">',
  ' <div style="font-size:10px;color:#78350f;font-weight:700;margin-bottom:5px;text-align:left">答對進度</div>',
  ' <div id="revProg"></div>',
  ' </div>',
  ' <div style="margin-bottom:10px">',
  ' <div style="font-size:10px;color:#78350f;font-weight:700;margin-bottom:5px;text-align:left">答錯次數</div>',
  ' <div id="revWrongDisp" style="display:flex;gap:7px;justify-content:flex-start"></div>',
  ' </div>',
  ' <div id="revQ" style="font-size:15px;font-weight:900;color:#92400e;margin:8px 0 5px;line-height:1.5"></div>',
  ' <div id="revNum" style="font-size:11px;color:#78350f;margin-bottom:4px"></div>',
  ' <div class="quizOpts" id="revOpts"></div>',
  '</div>',
  '</div>',
  '<div class="modal" id="gameOverModal" style="display:none">',
  '<div class="mbox"><div style="font-size:50px">💀</div><h2 style="color:#ef4444">挑戰失敗</h2><p>全員陣亡……</p>',
  ' <button class="mbtn blue" onclick="restartGame()">🔄 再次挑戰</button>',
  ' <button class="mbtn red" onclick="goBackToCamp()">🏕️ 返回營地</button>',
  '</div>',
  '</div>',
  '<div id="stageFlash"><div style="font-size:32px;font-weight:900;color:#4ade80;text-shadow:0 0 24px #4ade80;text-align:center;line-height:1.4;letter-spacing:2px" id="stageFlashMsg"></div></div>',
  '</div>',
].join('\n');

// ── 遊戲 JS 引擎 ──────────────────────────────────
var GAME_JS_BODY = [
  'const FOOD_FORMS = {',
  'normal:{ name:\'原味型\', emoji:\'🍙\', passive:\'普通型\',pIcon:\'✨\',sk1Icon:\'⚡\',sk2Icon:\'🌟\',sk1Name:\'雙彈衝刺\',sk2Name:\'能量爆發\',sk1Cd:4000,sk2Cd:12000,bulletColor:\'#fbbf24\',bulletDmg:12,spreadCount:0,speedBonus:0,defBonus:0 },',
  'burger:{ name:\'漢堡型\', emoji:\'🍔\', passive:\'受傷-15%\',pIcon:\'🛡️\',sk1Icon:\'💥\',sk2Icon:\'🌪️\',sk1Name:\'重擊彈\',sk2Name:\'旋轉彈幕\',sk1Cd:5000,sk2Cd:14000,bulletColor:\'#fb923c\',bulletDmg:18,spreadCount:0,speedBonus:0,defBonus:.15 },',
  'chili: { name:\'辣椒型\', emoji:\'🌶️\', passive:\'燃燒附加\',pIcon:\'🔥\',sk1Icon:\'🎯\',sk2Icon:\'☄️\',sk1Name:\'追蹤彈\',sk2Name:\'火焰衝刺\',sk1Cd:4500,sk2Cd:11000,bulletColor:\'#f97316\',bulletDmg:14,spreadCount:0,speedBonus:.15,defBonus:0 },',
  'tofu:  { name:\'豆腐型\', emoji:\'🧆\', passive:\'每5s回血\',pIcon:\'💎\',sk1Icon:\'🌀\',sk2Icon:\'💫\',sk1Name:\'護盾\',sk2Name:\'治癒波\',sk1Cd:6000,sk2Cd:15000,bulletColor:\'#a3e635\',bulletDmg:10,spreadCount:0,speedBonus:0,defBonus:0 },',
  'noodle:{ name:\'麵條型\', emoji:\'🍜\', passive:\'速度+30%\',pIcon:\'⚡\',sk1Icon:\'🌊\',sk2Icon:\'🌈\',sk1Name:\'波動連射\',sk2Name:\'彩虹亂射\',sk1Cd:3500,sk2Cd:10000,bulletColor:\'#f472b6\',bulletDmg:8,spreadCount:2,speedBonus:.3,defBonus:0 },',
  'rice:  { name:\'炒飯型\', emoji:\'🍚\', passive:\'金幣+50%\',pIcon:\'💰\',sk1Icon:\'💸\',sk2Icon:\'🏆\',sk1Name:\'金幣彈\',sk2Name:\'黃金護罩\',sk1Cd:4000,sk2Cd:13000,bulletColor:\'#fde047\',bulletDmg:11,spreadCount:0,speedBonus:0,defBonus:0 },',
  'ramen: { name:\'豚骨型\', emoji:\'🍲\', passive:\'爆擊+回血\',pIcon:\'🍜\',sk1Icon:\'🌡️\',sk2Icon:\'💥\',sk1Name:\'熱湯潑灑\',sk2Name:\'骨湯爆炸\',sk1Cd:4500,sk2Cd:13000,bulletColor:\'#fb7185\',bulletDmg:13,spreadCount:1,speedBonus:0,defBonus:.08 },',
  'sushi: { name:\'壽司型\', emoji:\'🍣\', passive:\'速度+爆擊\',pIcon:\'🔮\',sk1Icon:\'🌊\',sk2Icon:\'🎯\',sk1Name:\'魚波\',sk2Name:\'精準連擊\',sk1Cd:3800,sk2Cd:11500,bulletColor:\'#818cf8\',bulletDmg:12,spreadCount:1,speedBonus:.2,defBonus:0 },',
  'steak: { name:\'牛排型\', emoji:\'🥩\', passive:\'攻擊+爆擊\',pIcon:\'💪\',sk1Icon:\'🔥\',sk2Icon:\'💢\',sk1Name:\'火炙彈\',sk2Name:\'牛排衝擊\',sk1Cd:5000,sk2Cd:14000,bulletColor:\'#ef4444\',bulletDmg:22,spreadCount:0,speedBonus:0,defBonus:0 },',
  '};',
  'const qaBank=[',
  '{q:\'發現吐司有一小塊發霉，正確處理方式是？\',opts:[\'切掉發霉處繼續吃\',\'煮熟再吃\',\'整包直接丟棄\',\'放冷凍殺菌\'],ans:2},',
  '{q:\'牛肉哪個部位最嫩？\',opts:[\'肩胛肉\',\'菲力（里脊）\',\'牛腱\',\'牛腩\'],ans:1},',
  '{q:\'冰箱冷藏標準溫度是？\',opts:[\'0–4°C\',\'6–10°C\',\'15°C\',\'-5°C以下\'],ans:0},',
  '{q:\'梅納反應發生在什麼條件下？\',opts:[\'冷水長時間泡發\',\'高溫煎烤加工\',\'低溫舒肥慢煮\',\'醃漬加鹽靜置\'],ans:1},',
  '{q:\'食品存放的「危險溫度帶」是？\',opts:[\'0–7°C\',\'7–60°C\',\'60–100°C\',\'100°C以上\'],ans:1},',
  '{q:\'「FIFO」在廚房管理中代表？\',opts:[\'先進先出\',\'後進先出\',\'高溫消毒\',\'食安自主管理\'],ans:0},',
  '{q:\'「Sous Vide」是哪種烹調方式？\',opts:[\'高溫油炸\',\'真空低溫水浴\',\'大火快炒\',\'蒸氣燜煮\'],ans:1},',
  '{q:\'澱粉糊化需要哪個條件？\',opts:[\'冷水＋大力攪拌\',\'加熱＋水分\',\'冷凍＋鹽\',\'酸性環境＋油脂\'],ans:1},',
  '{q:\'豬肉安全的中心烹調溫度？\',opts:[\'55°C\',\'65°C\',\'75°C\',\'85°C\'],ans:2},',
  '{q:\'哪種食材解凍方式最不安全？\',opts:[\'室溫靜置解凍\',\'冷藏緩慢解凍\',\'微波爐解凍\',\'流水沖洗解凍\'],ans:0},',
  '{q:\'冰箱冷藏室應保持幾度以下？\',opts:[\'10°C以下\',\'7°C以下\',\'4°C以下\',\'0°C以下\'],ans:1},',
  '{q:\'廚師刀磨刀的正確角度約是？\',opts:[\'5度\',\'15–20度\',\'30度\',\'45度\'],ans:1},',
  '{q:\'生食與熟食應如何存放？\',opts:[\'可以放同層\',\'熟食放上層生食放下層\',\'生食放上層熟食放下層\',\'依食材種類分開\'],ans:1},',
  '{q:\'手部清洗搓洗應持續幾秒？\',opts:[\'5秒以上\',\'10秒以上\',\'20秒以上\',\'30秒以上\'],ans:2},',
  '{q:\'牛的哪個部位適合做牛排？\',opts:[\'牛腱\',\'牛腩\',\'肋眼（沙朗）\',\'牛尾\'],ans:2},',
  '{q:\'新鮮雞蛋應存放在幾度以下？\',opts:[\'15°C以下\',\'10°C以下\',\'7°C以下\',\'4°C以下\'],ans:2},',
  '];',
  'function randQa(){return qaBank[Math.floor(Math.random()*qaBank.length)];}',
  'const tr=SAVE.training||{atk:0,def:0,hp:0,stam:0,stamRegen:0,crit:0};',
  'const atkMult=1+(tr.atk||0)*.1;',
  'const defMult=1-(tr.def||0)*.08;',
  'const hpBonus=(tr.hp||0)*20;',
  'const stamBonus=(tr.stam||0)*10;',
  'const startForm=SAVE.equippedForm||\'normal\';',
  'const STAM_REGEN=0.012*(1+(tr.stamRegen||0)*.1);',
  'const AMULET_DEFS={',
  '\'廚神護符\':{atkBonus:.15},\'食安符\':{hpBonus:30},\'鮮度符\':{regenBonus:2},',
  '\'辛香符\':{critBonus:.08},\'溫度符\':{defBonus:.1},\'時令符\':{goldBonus:.2},',
  '};',
  'function calcBonus(amlets){',
  'let b={atk:0,def:0,hp:0,regen:0,crit:0,gold:0};',
  'amlets.forEach(a=>{const d=AMULET_DEFS[a]||{};b.atk+=(d.atkBonus||0);b.def+=(d.defBonus||0);b.hp+=(d.hpBonus||0);b.regen+=(d.regenBonus||0);b.crit+=(d.critBonus||0);b.gold+=(d.goldBonus||0);});',
  'return b;',
  '}',
  'const equippedAmulets=SAVE.equip?.amulets?.filter(Boolean)||[];',
  'const myAmuletBonus=calcBonus(equippedAmulets);',
  'const canvas=document.getElementById(\'gameCanvas\');',
  'const ctx=canvas.getContext(\'2d\');',
  'let CW=0,CH=0;',
  'function resize(){const gc=document.getElementById(\'gc\');CW=gc.clientWidth;CH=gc.clientHeight;canvas.width=CW;canvas.height=CH;}',
  'function safeResize(){resize();if(CW===0||CH===0){requestAnimationFrame(safeResize);return;}buildStars();}',
  'document.addEventListener(\'DOMContentLoaded\',()=>requestAnimationFrame(safeResize));',
  'window.addEventListener(\'resize\',()=>{resize();buildStars();});',
  'let gold=SAVE.gold||0,score=0,stage=1,gameRunning=false,stageCleared=false;',
  'let currentForm={...FOOD_FORMS[startForm]||FOOD_FORMS.normal};',
  'let sk1Cd=0,sk2Cd=0,passiveTimer=0;',
  'let pCds=[0,0];',
  'let spawnTimer=0,spawnQueue=[],bossSpawned=false;',
  'let stamina=100+stamBonus;',
  'const maxStamina=100+stamBonus;',
  'let currentWeapon=\'ranged\';',
  'let dodgeCd=0;',
  'const DODGE_CD=22000,DODGE_DUR=1000;',
  'let swipeAnim={active:false,progress:0,color:\'#d97706\'};',
  '',
  'let stars=[];',
  'function buildStars(){stars=[];for(let i=0;i<50;i++)stars.push({x:Math.random()*CW,y:Math.random()*CH,spd:.3+Math.random()*.8,r:1+Math.random()*2});}',
  'const player={x:0,y:0,radius:22,hp:100+hpBonus,maxHp:100+hpBonus,invTimer:0,weaponCd:0,speed:3.5,shieldActive:false,shieldHp:0};',
  'let pointer={x:0,y:0};',
  'const jWrap=document.getElementById(\'joystickWrap\');',
  'const jThumb=document.getElementById(\'joystickThumb\');',
  'let jActive=false,jTouchId=null,jDx=0,jDy=0;',
  'const JR=65;',
  'function moveJoystick(cx,cy){',
  'const r=jWrap.getBoundingClientRect();',
  'const cx2=r.left+r.width/2,cy2=r.top+r.height/2;',
  'let dx=cx-cx2,dy=cy-cy2;',
  'const d=Math.sqrt(dx*dx+dy*dy);',
  'if(d>JR){dx=dx/d*JR;dy=dy/d*JR;}',
  'jDx=dx/JR;jDy=dy/JR;',
  'jThumb.style.transform=\\`translate(calc(-50% + \\${dx}px), calc(-50% + \\${dy}px))\\`;',
  '}',
  'function resetJoystick(){jActive=false;jTouchId=null;jDx=0;jDy=0;jThumb.style.transform=\'translate(-50%,-50%)\';}',
  'jWrap.addEventListener(\'touchstart\',e=>{e.preventDefault();const t=e.changedTouches[0];jTouchId=t.identifier;jActive=true;moveJoystick(t.clientX,t.clientY);},{passive:false});',
  'window.addEventListener(\'touchmove\',e=>{if(!jActive)return;for(const t of e.changedTouches){if(t.identifier===jTouchId){moveJoystick(t.clientX,t.clientY);break;}}},{passive:false});',
  'window.addEventListener(\'touchend\',e=>{for(const t of e.changedTouches){if(t.identifier===jTouchId){resetJoystick();break;}}});',
  'const keys={};',
  'window.addEventListener(\'keydown\',e=>keys[e.code]=true);',
  'window.addEventListener(\'keyup\',e=>keys[e.code]=false);',
  'function getJoystickInput(){',
  'let dx=jDx,dy=jDy;',
  'if(keys[\'ArrowLeft\']||keys[\'KeyA\'])dx-=1;if(keys[\'ArrowRight\']||keys[\'KeyD\'])dx+=1;',
  'if(keys[\'ArrowUp\']||keys[\'KeyW\'])dy-=1;if(keys[\'ArrowDown\']||keys[\'KeyS\'])dy+=1;',
  'const m=Math.sqrt(dx*dx+dy*dy);if(m>1){dx/=m;dy/=m;}',
  'return{dx,dy};',
  '}',
  'let bullets=[],eBullets=[],enemies=[],particles=[],coins=[],texts=[];',
  'let boss=null;',
  'class Bullet{',
  'constructor(x,y,vx,vy,dmg,color,r,pierce=false,homing=false,burn=false){',
  ' Object.assign(this,{x,y,vx,vy,dmg,color,r,pierce,homing,burn,age:0,hitTargets:new Set()});',
  '}',
  'update(){',
  ' this.age++;',
  ' if(this.homing){',
  ' const t=findClosest(this.x,this.y,350);',
  ' if(t){const a=Math.atan2(t.y-this.y,t.x-this.x),ca=Math.atan2(this.vy,this.vx);let na=ca+(a-ca)*.12;this.vx=Math.cos(na)*8;this.vy=Math.sin(na)*8;}',
  ' }',
  ' this.x+=this.vx;this.y+=this.vy;',
  '}',
  'draw(){ctx.save();ctx.fillStyle=this.color;ctx.shadowBlur=8;ctx.shadowColor=this.color;ctx.beginPath();ctx.arc(this.x,this.y,this.r,0,Math.PI*2);ctx.fill();ctx.restore();}',
  'dead(){return this.x<-20||this.x>CW+20||this.y<-20||this.y>CH+20||this.age>200;}',
  '}',
  'class Enemy{',
  'constructor(x,y,type,hp,sv,stg=1){',
  'const sMult=1+stg*.12; // 每關強度+12%',
  'const sHp=Math.floor(hp*sMult);',
  'const sVy=(type===1?3:type===2?2.6:1.4)*(1+stg*.04);',
  'Object.assign(this,{x,y,type,maxHp:sHp,hp:sHp,scoreVal:sv,r:type===2?18:14,timer:0,atk:Math.ceil((type===2?18:type===3?12:8)*(1+stg*.1)),vy:sVy,vx:0,frozenTimer:0});',
  ' if(type===3)this.startX=x;',
  '}',
  'update(){',
  ' this.timer++;const sm=this.frozenTimer>0?.4:1;if(this.frozenTimer>0)this.frozenTimer--;',
  ' if(this.type===1){this.vx=player.x>this.x?1.2:-1.2;this.x+=this.vx*sm;this.y+=this.vy*sm;}',
  ' else if(this.type===2){this.y+=this.vy*sm;if(this.timer%90===0&&this.y>0&&this.y<CH*.5){const a=Math.atan2(player.y-this.y,player.x-this.x);eBullets.push(new Bullet(this.x,this.y,Math.cos(a)*4,Math.sin(a)*4,12,\'#f43f5e\',5));}}',
  ' else{this.x=this.startX+Math.sin(this.timer*.05)*50;this.y+=this.vy*sm;}',
  ' if(this.y>CH+60)this.hp=0;',
  '}',
  'draw(){',
  ' ctx.save();ctx.translate(this.x,this.y);',
  ' ctx.fillStyle=this.frozenTimer>0?\'#bfdbfe\':(this.type===1?\'#c084fc\':this.type===2?\'#f87171\':\'#fcd34d\');',
  ' ctx.shadowBlur=7;ctx.shadowColor=ctx.fillStyle;',
  ' ctx.beginPath();',
  ' if(this.type===1){ctx.moveTo(0,16);ctx.lineTo(13,-12);ctx.lineTo(-13,-12);}',
  ' else if(this.type===2){ctx.moveTo(0,16);ctx.lineTo(16,0);ctx.lineTo(0,-16);ctx.lineTo(-16,0);}',
  ' else ctx.arc(0,0,14,0,Math.PI*2);',
  ' ctx.closePath();ctx.fill();',
  ' if(this.hp<this.maxHp){ctx.fillStyle=\'#fde8c8\';ctx.fillRect(-12,-22,24,4);ctx.fillStyle=\'#ef4444\';ctx.fillRect(-12,-22,24*(this.hp/this.maxHp),4);}',
  ' ctx.restore();',
  '}',
  'takeDamage(amt){',
  ' this.hp-=amt*atkMult;addText(Math.floor(amt*atkMult).toString(),this.x,this.y,\'#78350f\');',
  ' if(this.hp<=0){',
  ' burst(this.x,this.y,\'#fb923c\',14);score+=this.scoreVal;',
  ' const goldChance=currentForm.name===\'炒飯型\'?.45:.3;',
  ' if(Math.random()<goldChance){',
  'const earn=currentForm.name===\'炒飯型\'?2:1;gold+=earn;',
  'addText(\'+\'+earn+\'💰\',this.x,this.y-20,\'#92400e\');updateHUD();',
  ' }',
  ' reportKill();',
  ' }',
  '}',
  '}',
  'class Boss extends Enemy{',
  'constructor(stg){',
  ' super(CW/2,-90,10,Math.floor((800+stg*300)*Math.pow(1/atkMult,.5)),stg<=1?800:stg===2?1800:3500);',
  ' this.r=64;this.phase=0;this.stg=stg;this.targetX=CW/2;this.targetY=130;this.atkTimer=0;this._defeated=false;',
  ' this.color=stg<=1?\'#f87171\':stg===2?\'#c084fc\':\'#f472b6\';',
  ' const sMax=Math.floor((300+stg*150));',
  ' this.shield=sMax;this.maxShield=sMax;this.shieldResetTimer=0;this.shieldBroken=false;',
  ' this.name=stg<=1?\'腐敗食神\':stg===2?\'毒素領主\':\'終焉主廚\';',
  ' document.getElementById(\'bossHud\').style.display=\'block\';',
  ' document.getElementById(\'bossName\').textContent=\'👿 \'+this.name;',
  ' updateBossHp();',
  '}',
  'update(){',
  ' this.timer++;if(this.y<this.targetY){this.y+=2.5;return;}',
  ' const sm=this.frozenTimer>0?.7:1;if(this.frozenTimer>0)this.frozenTimer--;',
  ' if(this.shieldBroken){',
  '  this.shieldResetTimer--;',
  '  updateBossShield();',
  '  if(this.shieldResetTimer<=0){',
  '   this.shield=this.maxShield;this.shieldBroken=false;',
  '   addText(\'🛡️護盾重置！\',this.x,this.y-50,\'#60a5fa\');',
  '   updateBossShield();',
  '  }',
  ' }',
  ' if(this.timer%100===0)this.targetX=50+Math.random()*(CW-100);',
  ' this.x+=(this.targetX-this.x)*.025*sm;this.y+=(this.targetY-this.y)*.025*sm;',
  ' this.atkTimer++;const intv=this.phase>=3?55:this.phase>=2?80:this.phase===1?120:180;',
  ' if(this.atkTimer>=intv){this.atkTimer=0;this.fire();}',
  '}',
  'fire(){',
  ' const bx=this.x,by=this.y+this.r,a=Math.atan2(player.y-by,player.x-bx);',
  ' if(this.phase===0){',
  '  for(let i=0;i<8;i++){const ang=(Math.PI*2/8)*i+(this.timer*.015);eBullets.push(new Bullet(this.x,this.y,Math.cos(ang)*2.4,Math.sin(ang)*2.4,14,this.color,8));}',
  ' }else if(this.phase===1){',
  '  for(let i=-2;i<=2;i++)eBullets.push(new Bullet(bx,by,Math.cos(a)+i*.6,Math.sin(a)+i*.4,18,\'#d8b4fe\',8));',
  ' }else if(this.phase===2){',
  '  for(let i=0;i<12;i++){const ang=(Math.PI*2/12)*i+(this.timer*.03);eBullets.push(new Bullet(this.x,this.y,Math.cos(ang)*4,Math.sin(ang)*4,16,this.color,12));}',
  '  if(this.atkTimer===0){const spd=5;eBullets.push(new Bullet(bx,by,Math.cos(a)*spd,Math.sin(a)*spd,20,\'#fbbf24\',14,false,true));}',
  ' }else{',
  '  for(let i=0;i<16;i++){const ang=(Math.PI*2/16)*i+(this.timer*.025);eBullets.push(new Bullet(this.x,this.y,Math.cos(ang)*3.2,Math.sin(ang)*3.2,14,this.color,10));}',
  '  for(let j=-1;j<=1;j++)eBullets.push(new Bullet(bx,by,Math.cos(a+j*.3)*6,Math.sin(a+j*.3)*6,22,\'#ff4444\',16));',
  ' }',
  '}',
  'draw(){',
  ' ctx.save();ctx.translate(this.x,this.y);ctx.shadowBlur=14;ctx.shadowColor=this.color;ctx.fillStyle=this.color;',
  ' ctx.beginPath();',
  ' if(this.stg<=1){ctx.moveTo(0,48);ctx.lineTo(48,0);ctx.lineTo(48,-26);ctx.lineTo(-48,-26);ctx.lineTo(-48,0);}',
  ' else if(this.stg===2){ctx.moveTo(0,52);ctx.lineTo(36,12);ctx.lineTo(52,-12);ctx.lineTo(0,-36);ctx.lineTo(-52,-12);ctx.lineTo(-36,12);}',
  ' else{ctx.rotate(this.timer*.018);ctx.arc(0,0,48,0,Math.PI*2);}',
  ' ctx.closePath();ctx.fill();',
  ' ctx.fillStyle=\'#fff\';ctx.shadowBlur=0;ctx.beginPath();ctx.arc(0,0,12+Math.sin(this.timer*.1)*6,0,Math.PI*2);ctx.fill();ctx.restore();',
  '}',
  'takeDamage(amt,isQa=false){',
  ' if(this._defeated)return;',
  ' if(this.shield>0&&!this.shieldBroken){',
  '  const shieldDmg=isQa?Math.floor(this.maxShield*.3):Math.floor(amt*atkMult*.5);',
  '  this.shield=Math.max(0,this.shield-shieldDmg);',
  '  addText(isQa?\'🛡️破盾！\':\'🛡️\'+shieldDmg,this.x,this.y-30,\'#60a5fa\');',
  '  updateBossShield();',
  '  if(this.shield<=0){this.shieldBroken=true;this.shieldResetTimer=20*60;addText(\'護盾破裂！\',this.x,this.y-50,\'#ef4444\');}',
  '  if(!isQa){this.hp-=Math.floor(amt*atkMult*.3);addText(Math.floor(amt*atkMult*.3).toString(),this.x,this.y,\'#92400e\');updateBossHp();return;}',
  ' }',
  '',
  ' this.hp-=amt*atkMult;addText(Math.floor(amt*atkMult).toString(),this.x,this.y,\'#92400e\');',
  ' updateBossHp();',
  'if(this.hp<this.maxHp*.75&&this.phase===0){this.phase=1;setTimeout(triggerQa,0);}',
  'if(this.hp<this.maxHp*.50&&this.phase===1){this.phase=2;setTimeout(triggerQa,0);}',
  'if(this.hp<this.maxHp*.25&&this.phase===2){this.phase=3;setTimeout(triggerQa,0);}',
  ' if(this.hp<=0){',
  ' this._defeated=true;',
  ' if(qaActive){qaActive=false;document.getElementById(\'qaOverlay\').style.display=\'none\';document.getElementById(\'pzr\').style.display=\'none\';}',
  ' document.getElementById(\'bossHud\').style.display=\'none\';',
  ' const bx=this.x,by=this.y;',
  ' const ec=[\'#ef4444\',\'#f97316\',\'#fbbf24\',\'#c084fc\',\'#38bdf8\'];',
  ' for(let i=0;i<4;i++)burst(bx+(Math.random()-.5)*50,by+(Math.random()-.5)*50,ec[i%5],10);',
  ' setTimeout(()=>{for(let i=0;i<5;i++)burst(bx+(Math.random()-.5)*70,by+(Math.random()-.5)*70,ec[i%5],10);addText(\'💥\',bx,by-30,\'#ef4444\');},200);',
  ' setTimeout(()=>{for(let i=0;i<5;i++)burst(bx+(Math.random()-.5)*80,by+(Math.random()-.5)*80,ec[i%5],10);},420);',
  ' setTimeout(()=>{for(let i=0;i<4;i++)burst(bx+(Math.random()-.5)*90,by+(Math.random()-.5)*90,ec[i%5],8);addText(\'+100💰\',bx,by-50,\'#d97706\');},650);',
  ' setTimeout(()=>coins.push(new Coin(bx+(Math.random()-.5)*60,by+(Math.random()-.5)*40),new Coin(bx+(Math.random()-.5)*60,by+(Math.random()-.5)*40)),100);',
  ' setTimeout(()=>coins.push(new Coin(bx+(Math.random()-.5)*70,by+(Math.random()-.5)*50),new Coin(bx+(Math.random()-.5)*70,by+(Math.random()-.5)*50)),300);',
  ' setTimeout(()=>coins.push(new Coin(bx+(Math.random()-.5)*60,by+(Math.random()-.5)*40),new Coin(bx+(Math.random()-.5)*60,by+(Math.random()-.5)*40)),500);',
  ' const fl2=document.getElementById(\'flash\');if(fl2){fl2.style.background=\'rgba(255,200,50,.5)\';fl2.style.opacity=\'1\';setTimeout(()=>{fl2.style.opacity=\'0\';},220);}',
  ' score+=this.scoreVal;gold+=100;updateHUD();reportBossKill();',
  ' stageCleared=true;gameRunning=false;',
  ' setTimeout(()=>{',
  'stage++;',
  'const fl=document.getElementById(\'stageFlash\'),fm=document.getElementById(\'stageFlashMsg\');',
  'fm.textContent=\'⚔️ 關卡 \'+stage;fl.style.display=\'flex\';',
  'setTimeout(()=>fl.style.display=\'none\',800);',
  'buildStage(stage);if(!window._gamePaused){gameRunning=true;last=performance.now();if(_rafId)cancelAnimationFrame(_rafId);requestAnimationFrame(loop);}',
  ' },600);',
  ' }',
  '}',
  '}',
  'class Coin{',
  'constructor(x,y){this.x=x;this.y=y;this.vx=(Math.random()-.5)*5;this.vy=-Math.random()*3-2;this.r=7;}',
  'update(){',
  ' this.vy+=.14;if(this.vy>4)this.vy=4;',
  ' const d=Math.hypot(player.x-this.x,player.y-this.y);',
  ' if(d<180){this.vx+=(player.x-this.x)*.005;this.vy+=(player.y-this.y)*.005;}',
  ' this.x+=this.vx;this.y+=this.vy;',
  ' if(this.x<8){this.x=8;this.vx*=-.5;}if(this.x>CW-8){this.x=CW-8;this.vx*=-.5;}',
  '}',
  'draw(){ctx.save();ctx.translate(this.x,this.y);ctx.fillStyle=\'#fde047\';ctx.beginPath();ctx.arc(0,0,this.r,0,Math.PI*2);ctx.fill();ctx.fillStyle=\'#ca8a04\';ctx.beginPath();ctx.arc(0,0,this.r-2,0,Math.PI*2);ctx.fill();ctx.restore();}',
  '}',
  'function burst(x,y,color,n){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=1+Math.random()*3.5;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-1,r:2+Math.random()*3,color,life:1,decay:.03+Math.random()*.03});}}',
  'function addText(t,x,y,color,sz=15,vy=-0.8){texts.push({t,x:x+(Math.random()-.5)*20,y,color,sz,life:1,vy});}',
  'function findClosest(x,y,range){let best=null,bd=range*range;for(const e of enemies){const d=(e.x-x)**2+(e.y-y)**2;if(d<bd){bd=d;best=e;}}if(boss&&!boss._defeated){const d=(boss.x-x)**2+(boss.y-y)**2;if(d<bd)best=boss;}return best;}',
  'function setWeapon(w){',
  'currentWeapon=w;',
  'const btn=document.getElementById(\'wpnToggle\');if(!btn)return;',
  'if(w===\'melee\'){btn.textContent=\'🗡️\';btn.style.borderColor=\'#7c3aed\';btn.style.background=\'rgba(167,139,250,.25)\';}',
  'else{btn.textContent=\'🏹\';btn.style.borderColor=\'#d97706\';btn.style.background=\'rgba(251,191,36,.2)\';}',
  '}',
  'function toggleWeapon(){setWeapon(currentWeapon===\'ranged\'?\'melee\':\'ranged\');}',
  'function dodge(){',
  'if(!gameRunning||dodgeCd>0||stamina<30)return;',
  'stamina=Math.max(0,stamina-30);dodgeCd=DODGE_CD;player.invTimer=60;',
  'burst(player.x,player.y,\'#88d4ff\',12);updateHUD();',
  'const btn=document.getElementById(\'dodgeBtnR\');if(btn){btn.classList.add(\'cooling\');setTimeout(()=>btn.classList.remove(\'cooling\'),DODGE_CD);}',
  '}',
  'function startSwipe(){swipeAnim={active:true,progress:0,color:currentForm.bulletColor||\'#d97706\',r:110};}',
  'const WEAPON_CD=10,MELEE_CD=28;',
  'function autoFire(){',
  'if(player.weaponCd>0){player.weaponCd--;return;}',
  'if(currentWeapon===\'melee\'){',
  ' player.weaponCd=MELEE_CD;',
  ' startSwipe();',
  ' const sRange=110;',
  ' enemies.forEach(e=>{const d=Math.sqrt((e.x-player.x)**2+(e.y-player.y)**2);if(d<sRange){e.takeDamage(currentForm.bulletDmg*2.2);burst(e.x,e.y,currentForm.bulletColor,5);}});',
  ' if(boss&&!boss._defeated&&Math.hypot(boss.x-player.x,boss.y-player.y)<sRange+20)boss.takeDamage(currentForm.bulletDmg*2.2);',
  '',
  ' let reflected=0;',
  ' for(let i=eBullets.length-1;i>=0;i--){',
  ' const b=eBullets[i];',
  ' if(reflected<4&&Math.hypot(b.x-player.x,b.y-player.y)<sRange+24){',
  'bullets.push(new Bullet(b.x,b.y,-b.vx*1.4,-b.vy*1.4,b.dmg*.8,currentForm.bulletColor,b.r+2));',
  'eBullets.splice(i,1);reflected++;',
  ' }',
  ' }',
  '} else {',
  ' player.weaponCd=WEAPON_CD;',
  ' const f=currentForm,sc=f.spreadCount||0;',
  ' if(sc>0){for(let i=-sc;i<=sc;i++)fire(player.x,player.y,Math.sin(i*.25)*10,-Math.cos(i*.25)*10,f.bulletColor,f.bulletDmg,5);}',
  ' else{fire(player.x,player.y,1,-12,f.bulletColor,f.bulletDmg,5);fire(player.x,player.y,-1,-12,f.bulletColor,f.bulletDmg,5);}',
  '}',
  '}',
  'function fire(x,y,vx,vy,color,dmg,r,pierce=false,homing=false){bullets.push(new Bullet(x,y,vx,vy,dmg*atkMult,color,r,pierce,homing,currentForm.name===\'辣椒型\'));}',
  'function updateSkillUI(){document.getElementById(\'sk1I\').textContent=currentForm.sk1Icon;document.getElementById(\'sk2I\').textContent=currentForm.sk2Icon;document.getElementById(\'skPI\').textContent=currentForm.pIcon;document.getElementById(\'sk1Cd\').style.display=\'none\';document.getElementById(\'sk2Cd\').style.display=\'none\';}',
  'function setForm(fid){const f=FOOD_FORMS[fid];if(!f)return;currentForm={...f};sk1Cd=0;sk2Cd=0;player.speed=3.5*(1+(f.speedBonus||0));updateSkillUI();document.getElementById(\'formBadge\').textContent=f.emoji+\' \'+f.name;document.getElementById(\'formPassive\').textContent=f.pIcon+\' \'+f.passive;}',
  'function useSkill1(){',
  'const SK1_COST=25;',
  'if(!gameRunning||stamina<SK1_COST)return;',
  'stamina=Math.max(0,stamina-SK1_COST);',
  'const f=currentForm;',
  'if(f.name===\'漢堡型\')fire(player.x,player.y,0,-14,f.bulletColor,35,9);',
  'else if(f.name===\'辣椒型\')fire(player.x,player.y,0,-10,f.bulletColor,25,7,false,true);',
  'else if(f.name===\'豆腐型\'){player.shieldActive=true;player.shieldHp=50;burst(player.x,player.y,\'#67e8f9\',18);addText(\'SHIELD\',player.x,player.y-20,\'#67e8f9\');}',
  'else if(f.name===\'麵條型\'){for(let i=-2;i<=2;i++)fire(player.x,player.y,i*2.5,-9,f.bulletColor,16,5);}',
  'else if(f.name===\'炒飯型\'){for(let i=-1;i<=1;i++)fire(player.x,player.y,i*1.5,-10,\'#fde047\',20,6);}',
  'else{fire(player.x-4,player.y,-1,-12,f.bulletColor,14,5);fire(player.x+4,player.y,1,-12,f.bulletColor,14,5);}',
  'burst(player.x,player.y,f.bulletColor,7);',
  '}',
  'function doDodge(){',
  'const DODGE_COST=30;',
  'if(!gameRunning||stamina<DODGE_COST||player.dodging)return;',
  'stamina=Math.max(0,stamina-DODGE_COST);updateHUD();',
  'player.dodging=true;player.invTimer=60; // 1秒無敵（60fps）',
  'const orig=player.alpha;player.alpha=0.25;',
  'addText(\'💨\',player.x,player.y-30,\'#60a5fa\');',
  'setTimeout(()=>{player.dodging=false;player.alpha=1;},1000);',
  '}',
  'function useSkill2(){',
  'const SK2_COST=40;',
  'if(!gameRunning||stamina<SK2_COST)return;',
  'stamina=Math.max(0,stamina-SK2_COST);',
  'const f=currentForm;',
  'if(f.name===\'漢堡型\'){for(let i=0;i<12;i++){const a=(i/12)*Math.PI*2;fire(player.x,player.y,Math.cos(a)*7,Math.sin(a)*7,f.bulletColor,20,6);}}',
  'else if(f.name===\'辣椒型\'){player.invTimer=90;enemies.forEach(e=>{if(Math.hypot(e.x-player.x,e.y-player.y)<80)e.hp-=40*atkMult;});if(boss&&!boss._defeated)boss.hp-=40*atkMult;burst(player.x,player.y,\'#f97316\',22);}',
  'else if(f.name===\'豆腐型\'){player.hp=Math.min(player.maxHp,player.hp+50);if(charSlots[activeChar])charSlots[activeChar].hp=player.hp;updateHUD();enemies.forEach(e=>e.takeDamage(22));if(boss&&!boss._defeated)boss.takeDamage(22);burst(player.x,player.y,\'#67e8f9\',22);}',
  'else if(f.name===\'麵條型\'){for(let i=0;i<14;i++){const a=(i/14)*Math.PI*2;fire(player.x,player.y,Math.cos(a)*7,Math.sin(a)*7,\'hsl(\'+(i*25)+\',100%,65%)\',14,5);}}',
  'else if(f.name===\'炒飯型\'){player.shieldActive=true;player.shieldHp=60;enemies.forEach(e=>e.takeDamage(30));if(boss&&!boss._defeated)boss.takeDamage(30);burst(player.x,player.y,\'#fde047\',20);}',
  'else{enemies.forEach(e=>e.takeDamage(30));if(boss&&!boss._defeated)boss.takeDamage(30);burst(player.x,player.y,\'#fbbf24\',18);}',
  '}',
  'let charSlots=[],activeChar=0;',
  'function initCharSlots(){',
  'charSlots=[];',
  'const baseHp=player.maxHp;',
  'const myHp=baseHp+(myAmuletBonus.hp||0);',
  'charSlots.push({name:SAVE.playerName||\'玩家\',emoji:currentForm.emoji,formId:startForm,hp:myHp,maxHp:myHp,alive:true});',
  'PARTNERS.forEach(p=>{',
  ' const pFormId=p.formId||\'normal\';',
  ' charSlots.push({name:p.name,emoji:(FOOD_FORMS[pFormId]||FOOD_FORMS.normal).emoji,formId:pFormId,hp:baseHp,maxHp:baseHp,alive:true});',
  '});',
  'activeChar=0;updateHUD();',
  '}',
  'function switchToNextAliveChar(){',
  'for(let i=activeChar+1;i<charSlots.length;i++){if(charSlots[i].alive){activeChar=i;return true;}}',
  'return false;',
  '}',
  'function switchToChar(slotIdx){',
  'if(!gameRunning&&slotIdx!==activeChar){}',
  'if(slotIdx===activeChar)return;',
  'if(!charSlots[slotIdx]||!charSlots[slotIdx].alive){addText(\'已陣亡！\',CW/2,CH*.5,\'#f87171\',20,0);return;}',
  'charSlots[activeChar].hp=player.hp;',
  'activeChar=slotIdx;',
  'const nextCh=charSlots[activeChar];',
  'player.hp=Math.max(1,nextCh.hp);player.maxHp=nextCh.maxHp;',
  'player.invTimer=45;player.x=Math.max(50,CW/2);player.y=Math.max(100,CH*.8);',
  'player.shieldActive=false;player.shieldHp=0;',
  'const switchForm=FOOD_FORMS[nextCh.formId]||currentForm;',
  'currentForm={...switchForm};player.speed=3.5*(1+(switchForm.speedBonus||0));',
  'updateSkillUI();',
  'document.getElementById(\'formBadge\').textContent=nextCh.emoji+\' \'+nextCh.name;',
  'document.getElementById(\'formPassive\').textContent=(switchForm.pIcon||\'✨\')+\' \'+switchForm.passive;',
  'updateHUD();burst(player.x,player.y,\'#a5b4fc\',20);',
  'addText(nextCh.emoji+\' \'+nextCh.name+\' 出擊！\',CW/2,CH*.45,\'#6366f1\',22,0);',
  '}',
  'function getPartnerPassiveBonus(){',
  'let b={atk:0,def:0,hp:0,regen:0,crit:0,gold:0};',
  'if(!charSlots||!charSlots.length)return b;',
  'charSlots.forEach((ch,i)=>{',
  ' if(i===activeChar||!ch.alive)return;',
  ' const f=FOOD_FORMS[ch.formId]||null;if(!f)return;',
  ' if(f.name===\'漢堡型\')b.def+=.06;if(f.name===\'炒飯型\')b.gold+=.2;',
  ' if(f.name===\'豆腐型\')b.regen+=1.5;if(f.name===\'壽司型\')b.crit+=.04;',
  ' if(f.name===\'牛排型\')b.atk+=.08;if(f.name===\'辣椒型\')b.atk+=.05;',
  ' if(f.name===\'麵條型\')b.crit+=.03;if(f.name===\'豚骨型\')b.regen+=1;',
  '});',
  'return b;',
  '}',
  'function updateHUD(){',
  'const bars=document.getElementById(\'charBars\');',
  'if(bars&&charSlots.length>0){',
  ' bars.innerHTML=charSlots.map((ch,i)=>{',
  ' const isActive=i===activeChar,alive=ch.alive;',
  ' const pct=Math.max(0,ch.hp/ch.maxHp*100);',
  ' const barColor=isActive?\'linear-gradient(90deg,#ef4444,#f87171)\':alive?\'linear-gradient(90deg,#fca5a5,#fecaca)\':\'#d1d5db\'',
  ' if(!alive)return \'<div class="charBar"><span class="charBarEmoji" style="opacity:.4">\'+ch.emoji+\'</span><div class="charBarInfo"><div class="charBarName" style="color:#9ca3af">\'+ch.name+\'</div><div style="font-size:11px;color:#9ca3af">💀 陣亡</div></div></div>\';',
  ' const canSwitch=!isActive&&alive;',
  ' return \'<div class="charBar" style="cursor:\'+(canSwitch?\'pointer\':\'default\')+\'"\'+(canSwitch?\' onclick="switchToChar(\'+i+\')"\':\'\')+\'>\'+',
  '\'<span class="charBarEmoji" style="font-size:\'+(isActive?\'26px\':\'20px\')+\';\'+(isActive?\'filter:drop-shadow(0 0 5px #f97316)\':\'opacity:.75\')+\'">\'+ch.emoji+\'</span>\'+',
  '\'<div class="charBarInfo">\'+',
  '\'<div class="charBarName" style="font-size:\'+(isActive?\'14px\':\'11px\')+\';color:\'+(isActive?\'#92400e\':\'#78350f\')+\'">\'+',
  '(isActive?\'▶ \':canSwitch?\'↩ \':\'\')+ch.name+',
  '\'</div>\'+',
  '\'<div class="charBarTrack" style="width:\'+(isActive?\'150px\':\'120px\')+\';height:\'+(isActive?\'14px\':\'10px\')+\'"><div class="charBarFill" style="width:\'+pct+\'%;background:\'+barColor+\'"></div></div>\'+',
  '\'<div class="charBarNum" style="font-size:\'+(isActive?\'13px\':\'11px\')+\'">\'+Math.ceil(ch.hp)+\' / \'+ch.maxHp+\'</div>\'+',
  '\'</div></div>\';',
  ' }).join(\'\');',
  '}',
  'const st=Math.max(0,Math.floor(stamina));',
  'document.getElementById(\'stamFill\').style.width=(st/maxStamina*100)+\'%\';',
  'document.getElementById(\'stamNum\').textContent=st+\'/\'+maxStamina;',
  'document.getElementById(\'coinDisp\').textContent=gold;',
  'document.getElementById(\'scoreDisp\').textContent=score;',
  'document.getElementById(\'lvlDisp\').textContent=stage;',
  'updatePSwitchUI();',
  '}',
  'function updatePSwitchUI(){',
  'if(!charSlots||!charSlots.length)return;',
  'charSlots.forEach((ch,i)=>{',
  ' const btn=document.getElementById(\'csBtn\'+i);if(!btn)return;',
  ' const emoji=document.getElementById(\'csEmoji\'+i),nameEl=document.getElementById(\'csName\'+i),hpFill=document.getElementById(\'csHpFill\'+i),deadEl=document.getElementById(\'csDead\'+i);',
  ' if(emoji)emoji.textContent=ch.emoji;',
  ' if(nameEl)nameEl.textContent=ch.name.slice(0,6);',
  ' const pct=Math.max(0,ch.hp/ch.maxHp*100);',
  ' if(hpFill){hpFill.style.width=pct+\'%\';hpFill.style.background=pct>50?\'#22c55e\':pct>25?\'#f59e0b\':\'#ef4444\';}',
  ' if(!ch.alive){btn.className=\'cSwBtn dead-char\';if(deadEl)deadEl.style.display=\'block\';}',
  ' else if(i===activeChar){btn.className=\'cSwBtn active-char\';if(deadEl)deadEl.style.display=\'none\';}',
  ' else{btn.className=\'cSwBtn\';if(deadEl)deadEl.style.display=\'none\';}',
  '});',
  '}',
  'function updateBossShield(){',
  'const shBar=document.getElementById(\'bossShieldBar\');',
  'if(!shBar||!boss)return;',
  'const pct=boss.maxShield>0?Math.max(0,boss.shield/boss.maxShield*100):0;',
  'shBar.style.width=pct+\'%\';',
  'shBar.style.background=boss.shieldBroken?\'#6b7280\':\'linear-gradient(90deg,#93c5fd,#3b82f6)\';',
  'const lbl=document.getElementById(\'bossShieldLbl\');',
  'if(lbl)lbl.textContent=boss.shieldBroken?\'護盾冷卻\'+Math.ceil(boss.shieldResetTimer/60)+\'s\':\'🛡️\'+boss.shield+\'/\'+boss.maxShield;',
  '}',
  'function updateBossHp(){if(boss&&!boss._defeated)document.getElementById(\'bossFill\').style.width=Math.max(0,boss.hp/boss.maxHp*100)+\'%\';}',
  'function hurtPlayer(raw){',
  'if(player.invTimer>0)return;',
  'let dmg=Math.ceil(raw*defMult);',
  'if(currentForm.defBonus)dmg=Math.ceil(dmg*(1-currentForm.defBonus));',
  'if(player.shieldActive){player.shieldHp-=dmg;burst(player.x,player.y,\'#67e8f9\',12);addText(\'SHIELD\',player.x,player.y-20,\'#67e8f9\');if(player.shieldHp<=0)player.shieldActive=false;return;}',
  'player.hp-=dmg;',
  'if(charSlots[activeChar])charSlots[activeChar].hp=player.hp;',
  'player.invTimer=22;burst(player.x,player.y,\'#ef4444\',10);addText(\'-\'+dmg,player.x,player.y-20,\'#ef4444\');updateHUD();',
  'if(player.hp<=0)playerDied();',
  '}',
  'function buildStage(s){',
  'bullets=[];eBullets=[];enemies=[];particles=[];coins=[];texts=[];',
  'boss=null;bossSpawned=false;stageCleared=false;spawnTimer=0;spawnQueue=[];',
  'player.x=Math.max(50,CW/2);player.y=Math.max(100,CH*.8);',
  'player.invTimer=30;player.shieldActive=false;player.shieldHp=0;player.weaponCd=0;player.alpha=1;player.dodging=false;',
  'if(charSlots.length>0&&charSlots[activeChar]){player.hp=charSlots[activeChar].hp;player.maxHp=charSlots[activeChar].maxHp;}',
  'pCds=[0,0];passiveTimer=0;',
  'document.getElementById(\'bossHud\').style.display=\'none\';',
  'document.getElementById(\'lvlDisp\').textContent=s;updateHUD();',
  'const WAVES=20+Math.floor(s/3);',
  'const baseFrame=200;',
  'for(let w=0;w<WAVES;w++){',
  ' const wf=baseFrame+w*180;',
  ' const count=2+Math.floor(s/2)+Math.floor(Math.random()*3); // 每波兵數隨關卡增加',
  ' for(let k=0;k<count;k++){',
  '  const t=Math.random()>.55?(Math.random()>.5?2:3):1;',
  '  spawnQueue.push({frame:wf+k*25,x:20+Math.random()*(CW-40),type:t,wave:w,stg:s});',
  ' }',
  '}',
  '}',
  'function tickSpawner(){',
  'spawnTimer++;',
  'while(spawnQueue.length&&spawnQueue[0].frame<=spawnTimer){const cfg=spawnQueue.shift();enemies.push(new Enemy(cfg.x,-20,cfg.type,18+stage*5,10*stage,cfg.stg||stage));}',
  'if(!bossSpawned&&!spawnQueue.length&&!enemies.length){bossSpawned=true;boss=new Boss(stage);}',
  '}',
  'let qaActive=false,qaTimer=0,qaAns=0;',
  'const QA_TIME=5000;',
  'function triggerQa(){',
  'if(qaActive||stageCleared)return;',
  'const qa=randQa();qaActive=true;qaTimer=QA_TIME;qaAns=qa.ans;',
  'document.getElementById(\'zAL\').textContent=\'A. \'+qa.opts[0];',
  'document.getElementById(\'zBL\').textContent=\'B. \'+qa.opts[1];',
  'document.getElementById(\'zCL\').textContent=\'C. \'+(qa.opts[2]||\'\');',
  'document.getElementById(\'zDL\').textContent=\'D. \'+(qa.opts[3]||\'\');',
  'document.getElementById(\'qaText\').textContent=qa.q;',
  'document.getElementById(\'timerFill\').style.width=\'100%\';',
  'document.getElementById(\'timerLabel\').textContent=(QA_TIME/1000).toFixed(1)+\'s\';',
  'document.getElementById(\'qaOverlay\').style.display=\'block\';',
  'document.getElementById(\'pzr\').style.display=\'block\';',
  'updatePzr();',
  '}',
  'function updatePzr(){const r=document.getElementById(\'pzr\');r.style.left=(player.x-18)+\'px\';r.style.top=(player.y-18)+\'px\';}',
  'function getPlayerZone(){const q=CW/4;if(player.x<q)return 0;if(player.x<q*2)return 1;if(player.x<q*3)return 2;return 3;}',
  'function resolveQa(dt){',
  'qaTimer-=dt;',
  'document.getElementById(\'timerFill\').style.width=(qaTimer/QA_TIME*100)+\'%\';',
  'document.getElementById(\'timerLabel\').textContent=Math.max(0,qaTimer/1000).toFixed(1)+\'s\';',
  'updatePzr();',
  'if(qaTimer<=0){endQa(getPlayerZone()===qaAns);}',
  '}',
  'function endQa(correct){',
  'qaActive=false;document.getElementById(\'qaOverlay\').style.display=\'none\';document.getElementById(\'pzr\').style.display=\'none\';',
  'const ids=[\'zA\',\'zB\',\'zC\',\'zD\'];',
  'if(correct){document.getElementById(ids[qaAns]).classList.add(\'cf\');setTimeout(()=>document.getElementById(ids[qaAns]).classList.remove(\'cf\'),700);burst(player.x,player.y,\'#4ade80\',16);}',
  'if(boss&&!boss._defeated)boss.takeDamage(boss.maxHp*.08,true);',
  'else{const wc=getPlayerZone();document.getElementById(ids[Math.min(3,wc)]).classList.add(\'wf\');setTimeout(()=>document.getElementById(ids[Math.min(3,wc)]).classList.remove(\'wf\'),600);hurtPlayer(45);burst(player.x,player.y,\'#ef4444\',20);}',
  '}',
  'let revCorrect=0,revWrong=0,revPool=[];',
  'function playerDied(){',
  'if(charSlots.length>0)charSlots[activeChar].alive=false;',
  'const hasNext=switchToNextAliveChar();',
  'if(hasNext){',
  ' const nextCh=charSlots[activeChar];',
  ' player.hp=Math.max(1,nextCh.hp);player.maxHp=nextCh.maxHp;',
  ' player.invTimer=50;player.x=Math.max(50,CW/2);player.y=Math.max(100,CH*.8);',
  ' player.shieldActive=false;player.shieldHp=0;',
  ' const switchForm=FOOD_FORMS[nextCh.formId]||currentForm;',
  ' currentForm={...switchForm};player.speed=3.5*(1+(switchForm.speedBonus||0));',
  ' updateSkillUI();',
  ' document.getElementById(\'formBadge\').textContent=nextCh.emoji+\' \'+nextCh.name;',
  ' document.getElementById(\'formPassive\').textContent=(switchForm.pIcon||\'✨\')+\' \'+switchForm.passive;',
  ' updateHUD();burst(player.x,player.y,\'#a5b4fc\',24);',
  ' addText(\'🔄 \'+nextCh.emoji+\' \'+nextCh.name+\' 出擊！\',CW/2,CH*.45,\'#6366f1\',22,0);',
  ' return;',
  '}',
  'gameRunning=false;revCorrect=0;revWrong=0;',
  'revPool=[...qaBank].sort(()=>Math.random()-.5);',
  'document.getElementById(\'revModal\').style.display=\'flex\';',
  'updateCharStatusUI();drawRevProg();nextRevQ();',
  '}',
  'function updateCharStatusUI(){',
  'const row=document.getElementById(\'charStatusRow\');if(!row)return;',
  'row.innerHTML=charSlots.map((ch,i)=>',
  ' \'<div style="display:flex;flex-direction:column;align-items:center;gap:2px;opacity:\'+(ch.alive?1:.35)+\'">\'+',
  ' \'<div style="font-size:\'+(i===activeChar?\'24px\':\'20px\')+\'">\'+ch.emoji+\'</div>\'+',
  ' \'<div style="font-size:10px;font-weight:900;color:\'+(i===activeChar?\'#059669\':\'#78350f\')+\'">\'+ch.name+\'</div>\'+',
  ' \'<div style="font-size:11px">\'+(ch.alive?\'❤️\':\'💀\')+\'</div></div>\'',
  ').join(\'\');',
  '}',
  'function drawRevProg(){',
  'document.getElementById(\'revProg\').innerHTML=Array.from({length:5},(_,i)=>\'<span style="font-size:22px;line-height:1">\'+(i<revCorrect?\'💚\':\'🩶\')+\'</span>\').join(\'\');',
  'document.getElementById(\'revWrongDisp\').innerHTML=Array.from({length:3},(_,i)=>\'<span style="font-size:22px;line-height:1">\'+(i<revWrong?\'❌\':\'🔘\')+\'</span>\').join(\'\');',
  '}',
  'let curRevQ=null;',
  'function nextRevQ(){',
  'if(!revPool.length)revPool=[...qaBank].sort(()=>Math.random()-.5);',
  'curRevQ=revPool.pop();',
  'document.getElementById(\'revQ\').textContent=curRevQ.q;',
  'document.getElementById(\'revNum\').textContent=\'答對 \'+revCorrect+\' / 5　答錯 \'+revWrong+\' / 3\';',
  'const opts=document.getElementById(\'revOpts\');opts.innerHTML=\'\';',
  '[\'A\',\'B\',\'C\',\'D\'].slice(0,curRevQ.opts.length).forEach((l,i)=>{',
  ' const btn=document.createElement(\'button\');btn.className=\'qopt\';btn.textContent=l+\'. \'+curRevQ.opts[i];',
  ' btn.onclick=()=>{',
  ' const ok=i===curRevQ.ans;btn.className=\'qopt \'+(ok?\'correct\':\'wrong\');',
  ' opts.querySelectorAll(\'.qopt\').forEach((b,j)=>{b.onclick=null;if(j===curRevQ.ans)b.className=\'qopt correct\';});',
  ' if(ok){revCorrect++;drawRevProg();if(revCorrect>=5){setTimeout(()=>{document.getElementById(\'revModal\').style.display=\'none\';goBackToCamp();},700);return;}}',
  ' else{revWrong++;drawRevProg();if(revWrong>=3){setTimeout(()=>{document.getElementById(\'revModal\').style.display=\'none\';gold=0;window.parent.postMessage({type:\'FR_PENALTY_RETURN\'},\'*\');},900);return;}}',
  ' setTimeout(nextRevQ,900);',
  ' };opts.appendChild(btn);',
  '});',
  '}',
  'function drawBg(){',
  'const g=ctx.createLinearGradient(0,0,0,CH);g.addColorStop(0,\'#fdf8f0\');g.addColorStop(1,\'#f5ede0\');',
  'ctx.fillStyle=g;ctx.fillRect(0,0,CW,CH);',
  'ctx.fillStyle=\'rgba(253,251,247,.8)\';',
  'stars.forEach((s,i)=>{const y=((s.y)%CH+CH)%CH;if(i%5===0){ctx.beginPath();ctx.ellipse(s.x,y,s.r*6,s.r*2.5,0,0,Math.PI*2);ctx.fill();}});',
  'ctx.strokeStyle=\'rgba(180,160,130,.07)\';ctx.lineWidth=1;',
  'for(let x=0;x<CW;x+=30){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,CH);ctx.stroke();}',
  'for(let y=0;y<CH;y+=30){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(CW,y);ctx.stroke();}',
  '}',
  'function drawPlayer(){',
  'if(player.invTimer>0&&!player.dodging&&Math.floor(Date.now()/80)%2===0)return;',
  'ctx.save();ctx.translate(player.x,player.y);',
  'ctx.globalAlpha=player.alpha||1;',
  'ctx.font=\'36px sans-serif\';ctx.textBaseline=\'middle\';ctx.textAlign=\'center\';ctx.fillText(currentForm.emoji,0,0);',
  'ctx.fillStyle=\'#fb923c\';ctx.globalAlpha=.5+Math.random()*.35;',
  'ctx.beginPath();ctx.moveTo(-7,15);ctx.lineTo(0,26+Math.random()*8);ctx.lineTo(7,15);ctx.closePath();ctx.fill();',
  'ctx.globalAlpha=1;',
  'if(player.shieldActive){ctx.strokeStyle=\'#67e8f9\';ctx.lineWidth=3;ctx.globalAlpha=.55;ctx.beginPath();ctx.arc(0,0,26,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=.12;ctx.fillStyle=\'#67e8f9\';ctx.fill();ctx.globalAlpha=1;}',
  'if(swipeAnim.active){',
  ' const p=swipeAnim.progress;',
  ' const r=swipeAnim.r||110;',
  ' // 從左(-π)掃到右(0)：startA=-π+(1-p)*π → endA固定0',
  ' // progress 0→1 時，startA 從-π掃到0（即從左到右）',
  ' const startA=-Math.PI*(1-p); // 從左邊開始',
  ' const endA=0;                 // 到右邊結束',
  ' ctx.save();',
  ' // 主扇形',
  ' ctx.globalAlpha=(1-p)*.6;',
  ' ctx.fillStyle=swipeAnim.color;',
  ' ctx.beginPath();',
  ' ctx.moveTo(0,0);',
  ' ctx.arc(0,0,r,startA,endA,false);',
  ' ctx.closePath();',
  ' ctx.fill();',
  ' // 內層較淡',
  ' ctx.globalAlpha=(1-p)*.2;',
  ' ctx.beginPath();',
  ' ctx.moveTo(0,0);',
  ' ctx.arc(0,0,r*.6,startA,endA,false);',
  ' ctx.closePath();',
  ' ctx.fill();',
  ' // 弧形邊線',
  ' ctx.globalAlpha=(1-p)*.85;',
  ' ctx.strokeStyle=swipeAnim.color;',
  ' ctx.lineWidth=3;',
  ' ctx.beginPath();',
  ' ctx.arc(0,0,r,startA,endA,false);',
  ' ctx.stroke();',
  ' ctx.restore();',
  '}',
  'ctx.globalAlpha=1;',
  'ctx.restore();',
  '}',
  'let last=0;',
  'function loop(ts){',
  'if(!gameRunning||stageCleared)return;',
  'if(!ctx||ctx.isContextLost&&ctx.isContextLost()){',
  ' ctx=canvas.getContext(\'2d\');if(!ctx)return;',
  '}',
  'const dt=Math.min(ts-last,16);last=ts; // iOS: 限制最大dt=1幀，防止背景恢復後跳幀',
  'stars.forEach(s=>{s.y+=s.spd;if(s.y>CH){s.y=0;s.x=Math.random()*CW;}});',
  'const ji=getJoystickInput();',
  'const spd=player.speed*(currentWeapon===\'melee\'?1.1:1);',
  'player.x=Math.max(player.radius,Math.min(CW-player.radius,player.x+ji.dx*spd));',
  'player.y=Math.max(player.radius,Math.min(CH-player.radius,player.y+ji.dy*spd));',
  'pointer.x=player.x;pointer.y=player.y;',
  'if(player.invTimer>0)player.invTimer--;',
  'if(dodgeCd>0)dodgeCd-=dt;',
  'if(swipeAnim.active){swipeAnim.progress+=dt/180;if(swipeAnim.progress>=1)swipeAnim.active=false;}',
  'stamina=Math.min(maxStamina,stamina+STAM_REGEN*dt);',
  'const st=Math.max(0,Math.floor(stamina));',
  'if(Math.floor(ts/100)%3===0){document.getElementById(\'stamFill\').style.width=(st/maxStamina*100)+\'%\';document.getElementById(\'stamNum\').textContent=st+\'/\'+maxStamina;}',
  'if(sk1Cd>0){sk1Cd-=dt;const el=document.getElementById(\'sk1Cd\');el.style.display=\'flex\';el.textContent=Math.ceil(sk1Cd/1000)+\'s\';if(sk1Cd<=0){sk1Cd=0;el.style.display=\'none\';}}',
  'if(sk2Cd>0){sk2Cd-=dt;const el=document.getElementById(\'sk2Cd\');el.style.display=\'flex\';el.textContent=Math.ceil(sk2Cd/1000)+\'s\';if(sk2Cd<=0){sk2Cd=0;el.style.display=\'none\';}}',
  'const pb=getPartnerPassiveBonus();',
  'if((currentForm.name===\'豆腐型\'||currentForm.name===\'豚骨型\'||pb.regen>0)&&passiveTimer>=5000){',
  ' passiveTimer=0;const regen=(pb.regen||0)+(currentForm.name===\'豆腐型\'||currentForm.name===\'豚骨型\'?5:0);',
  ' player.hp=Math.min(player.maxHp,player.hp+regen);if(charSlots[activeChar])charSlots[activeChar].hp=player.hp;burst(player.x,player.y,\'#a3e635\',5);',
  '} else passiveTimer+=dt;',
  'if(qaActive)resolveQa(dt);',
  'if(!bossSpawned)tickSpawner();',
  'for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];e.update();if(Math.hypot(player.x-e.x,player.y-e.y)<player.radius+e.r&&player.invTimer<=0)hurtPlayer(10);if(e.hp<=0)enemies.splice(i,1);}',
  'if(boss&&!boss._defeated){boss.update();if(Math.hypot(player.x-boss.x,player.y-boss.y)<player.radius+boss.r&&player.invTimer<=0)hurtPlayer(20);}',
  'for(let i=bullets.length-1;i>=0;i--){',
  ' const b=bullets[i];b.update();let rm=false;',
  ' for(const e of enemies){if(b.hitTargets.has(e))continue;if(Math.hypot(b.x-e.x,b.y-e.y)<b.r+e.r){e.takeDamage(b.dmg);burst(b.x,b.y,b.color,3);if(b.burn)setTimeout(()=>{if(e.hp>0)e.hp-=4;},800);if(!b.pierce)rm=true;else b.hitTargets.add(e);break;}}',
  ' if(boss&&!boss._defeated&&!qaActive&&Math.hypot(b.x-boss.x,b.y-boss.y)<b.r+boss.r){boss.takeDamage(b.dmg);burst(b.x,b.y,b.color,3);rm=true;}',
  ' if(b.dead())rm=true;if(rm)bullets.splice(i,1);',
  '}',
  'for(let i=eBullets.length-1;i>=0;i--){const b=eBullets[i];b.update();if(!qaActive&&Math.hypot(b.x-player.x,b.y-player.y)<b.r+player.radius&&player.invTimer<=0){hurtPlayer(b.dmg);burst(b.x,b.y,b.color,5);eBullets.splice(i,1);continue;}if(b.dead())eBullets.splice(i,1);}',
  'if(player.weaponCd>0)player.weaponCd--; else if(!qaActive)autoFire();',
  'for(let i=coins.length-1;i>=0;i--){const c=coins[i];c.update();if(Math.hypot(player.x-c.x,player.y-c.y)<player.radius+c.r){gold+=1;addText(\'+1💰\',c.x,c.y,\'#92400e\');updateHUD();coins.splice(i,1);continue;}if(c.y>CH+20)coins.splice(i,1);}',
  'if(particles.length>200)particles.length=200;',
  'if(eBullets.length>120)eBullets.length=120;',
  'if(texts.length>25)texts.length=25;',
  'for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx;p.y+=p.vy;p.vy+=.1;p.life-=p.decay;if(p.life<=0)particles.splice(i,1);}',
  'for(let i=texts.length-1;i>=0;i--){const t=texts[i];t.y+=t.vy;t.life-=.022;if(t.life<=0)texts.splice(i,1);}',
  'ctx.clearRect(0,0,CW,CH);drawBg();',
  'coins.forEach(c=>c.draw());',
  'enemies.forEach(e=>e.draw());if(boss&&!boss._defeated)boss.draw();',
  'drawPlayer();',
  'bullets.forEach(b=>b.draw());eBullets.forEach(b=>b.draw());',
  'particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();});ctx.globalAlpha=1;',
  'texts.forEach(t=>{ctx.globalAlpha=Math.max(0,t.life);ctx.fillStyle=t.color;ctx.font=\'bold \'+t.sz+\'px sans-serif\';ctx.textAlign=\'center\';ctx.fillText(t.t,t.x,t.y);});ctx.globalAlpha=1;ctx.textAlign=\'left\';',
  '_rafId=requestAnimationFrame(loop);',
  '}',
  'function reportKill(){window.parent.postMessage({type:\'FR_QUEST_KILL\'},\'*\');}',
  'function reportBossKill(){window.parent.postMessage({type:\'FR_BOSS_KILLED\',gold},\'*\');}',
  'function goBackToCamp(){window.parent.postMessage({type:\'FR_BACK_TO_CAMP\',gold},\'*\');}',
  'function startGame(){',
  'document.getElementById(\'startModal\').style.display=\'none\';',
  'setForm(startForm);buildStage(stage);initCharSlots();',
  'if(!window._gamePaused){gameRunning=true;last=performance.now();if(_rafId)cancelAnimationFrame(_rafId);requestAnimationFrame(loop);}',
  '}',
  'function restartGame(){',
  'const savedStage=parseInt(localStorage.getItem(\'fr_last_stage\')||\'1\');',
  'stage=Math.max(1,savedStage-1)||1;score=0;[\'gameOverModal\',\'revModal\'].forEach(id=>document.getElementById(id).style.display=\'none\');',
  'setForm(startForm);buildStage(stage);initCharSlots();updateHUD();',
  'if(!window._gamePaused){gameRunning=true;last=performance.now();if(_rafId)cancelAnimationFrame(_rafId);requestAnimationFrame(loop);}',
  '}',
  '',
  'function initUI(){',
  'if(PARTNERS.length>0)document.getElementById(\'partnerPreview\').textContent=\'🤝 夥伴：\'+PARTNERS.map(p=>p.name).join(\'、\');',
  'if(!PARTNERS.length)document.getElementById(\'charSwitchBar\').style.display=\'none\';',
  'const ff=FOOD_FORMS[startForm]||FOOD_FORMS.normal;',
  'document.getElementById(\'startEmoji\').textContent=ff.emoji;',
  'document.getElementById(\'formBadge\').textContent=ff.emoji+\' \'+ff.name;',
  'document.getElementById(\'formPassive\').textContent=ff.pIcon+\' \'+ff.passive;',
  'updateSkillUI();updateHUD();',
  '}',
  'function safeInit(){if(CW===0||CH===0){requestAnimationFrame(safeInit);return;}initUI();}',
  '',
  'let _rafId=null;',
  'const _origRaf=window.requestAnimationFrame.bind(window);',
  'window.requestAnimationFrame=function(cb){_rafId=_origRaf(cb);return _rafId;};',
  '',
  'document.addEventListener(\'visibilitychange\',()=>{',
  ' if(document.hidden){',
  '  if(_rafId){cancelAnimationFrame(_rafId);_rafId=null;}',
  '  if(gameRunning){window._gamePaused=true;gameRunning=false;}',
  ' } else {',
  '  last=performance.now();',
  '  if(window._gamePaused){',
  '   window._gamePaused=false;',
  '   if(!ctx||!canvas){',
  '    canvas=document.getElementById(\'gameCanvas\');',
  '    if(canvas)ctx=canvas.getContext(\'2d\');',
  '   }',
  '   if(!_rafId&&ctx){',
  '    gameRunning=true;',
  '    _rafId=requestAnimationFrame(loop);',
  '   }',
  '  }',
  ' }',
  '});',
  '',
  'window.addEventListener(\'pagehide\',()=>{',
  ' if(_rafId){cancelAnimationFrame(_rafId);_rafId=null;}',
  ' gameRunning=false;',
  '});',
  '',
  'window.addEventListener(\'pageshow\',(e)=>{',
  ' if(e.persisted&&window._gamePaused){',
  '  last=performance.now();',
  '  window._gamePaused=false;',
  '  if(!_rafId&&ctx){',
  '   gameRunning=true;',
  '   _rafId=requestAnimationFrame(loop);',
  '  }',
  ' }',
  '});',
  '',
  'window.addEventListener(\'message\',e=>{',
  ' if(!e.data||!e.data.type)return;',
  ' if(e.data.type===\'PAUSE_GAME\'){',
  '  if(_rafId){cancelAnimationFrame(_rafId);_rafId=null;}',
  '  if(gameRunning){window._gamePaused=true;gameRunning=false;}',
  ' } else if(e.data.type===\'RESUME_GAME\'){',
  '  if(window._gamePaused&&!_rafId&&ctx){',
  '   last=performance.now();window._gamePaused=false;gameRunning=true;',
  '   _rafId=requestAnimationFrame(loop);',
  '  }',
  ' }',
  '},false);',
  '',
  'requestAnimationFrame(safeInit);',
].join('\n');
